// <auto-generated />
using CatalogoAgil.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CatalogoAgil.DataAccess.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20250715024847_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CatalogoAgil.DataAccess.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("ProductCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductQuantity")
                        .HasColumnType("int");

                    b.Property<bool>("ProductStatus")
                        .HasColumnType("bit");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            ProductCategory = "P",
                            ProductDescription = "Combustível tipo comum",
                            ProductName = "Gasolina Comum",
                            ProductPrice = 6.00m,
                            ProductQuantity = 1000,
                            ProductStatus = true
                        },
                        new
                        {
                            ProductId = 2,
                            ProductCategory = "P",
                            ProductDescription = "Combustível com aditivos",
                            ProductName = "Gasolina Aditivada",
                            ProductPrice = 6.30m,
                            ProductQuantity = 800,
                            ProductStatus = true
                        },
                        new
                        {
                            ProductId = 3,
                            ProductCategory = "P",
                            ProductDescription = "Álcool combustível",
                            ProductName = "Etanol",
                            ProductPrice = 4.20m,
                            ProductQuantity = 500,
                            ProductStatus = true
                        },
                        new
                        {
                            ProductId = 4,
                            ProductCategory = "P",
                            ProductDescription = "Diesel de baixa emissão",
                            ProductName = "Diesel S10",
                            ProductPrice = 5.80m,
                            ProductQuantity = 1200,
                            ProductStatus = true
                        },
                        new
                        {
                            ProductId = 5,
                            ProductCategory = "B",
                            ProductDescription = "350ml - Diversos sabores",
                            ProductName = "Refrigerante Lata",
                            ProductPrice = 5.00m,
                            ProductQuantity = 100,
                            ProductStatus = true
                        },
                        new
                        {
                            ProductId = 6,
                            ProductCategory = "B",
                            ProductDescription = "500ml - com ou sem gás",
                            ProductName = "Água Mineral",
                            ProductPrice = 3.00m,
                            ProductQuantity = 150,
                            ProductStatus = true
                        },
                        new
                        {
                            ProductId = 7,
                            ProductCategory = "B",
                            ProductDescription = "Copo 100ml",
                            ProductName = "Café Expresso",
                            ProductPrice = 2.50m,
                            ProductQuantity = 50,
                            ProductStatus = true
                        },
                        new
                        {
                            ProductId = 8,
                            ProductCategory = "A",
                            ProductDescription = "Frango ou atum",
                            ProductName = "Sanduíche Natural",
                            ProductPrice = 7.50m,
                            ProductQuantity = 30,
                            ProductStatus = true
                        },
                        new
                        {
                            ProductId = 9,
                            ProductCategory = "A",
                            ProductDescription = "Diversos sabores",
                            ProductName = "Salgadinho Chips",
                            ProductPrice = 4.00m,
                            ProductQuantity = 40,
                            ProductStatus = true
                        },
                        new
                        {
                            ProductId = 10,
                            ProductCategory = "A",
                            ProductDescription = "Barrinha 25g",
                            ProductName = "Chocolate",
                            ProductPrice = 2.80m,
                            ProductQuantity = 60,
                            ProductStatus = true
                        },
                        new
                        {
                            ProductId = 11,
                            ProductCategory = "A",
                            ProductDescription = "Sortida",
                            ProductName = "Bala",
                            ProductPrice = 1.00m,
                            ProductQuantity = 100,
                            ProductStatus = true
                        },
                        new
                        {
                            ProductId = 12,
                            ProductCategory = "A",
                            ProductDescription = "Sortido",
                            ProductName = "Chiclete",
                            ProductPrice = 1.50m,
                            ProductQuantity = 80,
                            ProductStatus = true
                        },
                        new
                        {
                            ProductId = 13,
                            ProductCategory = "O",
                            ProductDescription = "Lubrificante 1L",
                            ProductName = "Óleo de Motor",
                            ProductPrice = 30.00m,
                            ProductQuantity = 20,
                            ProductStatus = true
                        },
                        new
                        {
                            ProductId = 14,
                            ProductCategory = "O",
                            ProductDescription = "DOT 4",
                            ProductName = "Fluido de Freio",
                            ProductPrice = 25.00m,
                            ProductQuantity = 15,
                            ProductStatus = true
                        },
                        new
                        {
                            ProductId = 15,
                            ProductCategory = "O",
                            ProductDescription = "1L Pronto uso",
                            ProductName = "Aditivo Radiador",
                            ProductPrice = 22.00m,
                            ProductQuantity = 10,
                            ProductStatus = true
                        },
                        new
                        {
                            ProductId = 16,
                            ProductCategory = "O",
                            ProductDescription = "Farol H7",
                            ProductName = "Lâmpada Automotiva",
                            ProductPrice = 15.00m,
                            ProductQuantity = 10,
                            ProductStatus = true
                        },
                        new
                        {
                            ProductId = 17,
                            ProductCategory = "A",
                            ProductDescription = "Odorizador em cartão",
                            ProductName = "Desodorizador de Carro",
                            ProductPrice = 6.00m,
                            ProductQuantity = 25,
                            ProductStatus = true
                        },
                        new
                        {
                            ProductId = 18,
                            ProductCategory = "O",
                            ProductDescription = "Pacote com 5 unidades",
                            ProductName = "Pano Multiuso",
                            ProductPrice = 10.00m,
                            ProductQuantity = 20,
                            ProductStatus = true
                        },
                        new
                        {
                            ProductId = 19,
                            ProductCategory = "O",
                            ProductDescription = "Para emergência veicular",
                            ProductName = "Cabo de Chupeta",
                            ProductPrice = 45.00m,
                            ProductQuantity = 5,
                            ProductStatus = true
                        },
                        new
                        {
                            ProductId = 20,
                            ProductCategory = "A",
                            ProductDescription = "USB Veicular",
                            ProductName = "Carregador de Celular",
                            ProductPrice = 20.00m,
                            ProductQuantity = 10,
                            ProductStatus = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
